name: PR Lint

on:
  pull_request:

jobs:
  # bump required tf version first
  # terraform-lint:
  #   uses: entur/gha-terraform/.github/workflows/lint.yml@v2
  #   with:
  #     directory: modules/bucket
  terraform-lint2:
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: examples/minimal
  terraform-lint3:
    uses: entur/gha-terraform/.github/workflows/lint.yml@v2
    with:
      directory: examples/minimal_test
