name: Call Validate PR

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  verify-pr:
    if: ${{ github.event_name == 'pull_request' }}
    uses: entur/gha-meta/.github/workflows/verify-pr.yml@v1
