name: Call Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
    with:
      path: "./"
      release_type: "terraform-module"
