name: Call Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: entur/gha-meta/.github/workflows/release.yml@v1
    with:
      path: "./"
      release_type: "terraform-module"
